#include "cmd_teacher_add_cancel_stu_chess.h"

PROTO_NAMESPACE_BEGIN

IMPLEMENT_COMMAND_RUNTIME_INFO(CommandType::TeacherAddCancelStuChess, CmdTeacherAddCancelStuChess, CommandCell)

PROTO_NAMESPACE_END