#include "cmd_teacher_sync_current_chess_board.h"

PROTO_NAMESPACE_BEGIN

IMPLEMENT_COMMAND_RUNTIME_INFO(CommandType::TeacherSyncCurrentChessBoard, CmdTeacherSyncCurrentChessBoard, CommandCell)

PROTO_NAMESPACE_END