#include "cmd_teacher_class_upload_ppt_files.h"

PROTO_NAMESPACE_BEGIN

IMPLEMENT_COMMAND_RUNTIME_INFO(CommandType::TeacherClassUploadPptFiles, CmdTeacherClassUploadPptFiles, CommandCell)

PROTO_NAMESPACE_END